input:
  dir: data/
  vcf: SIMDATA.vcf
  metadata: SIMDATA_metadata.tsv
  gff: SIMDATA.gff3
project_name: SIMDATA
cpu: 16.0
filter:
  maf: 0.05
  snp_miss: 0.1
  sample_miss: 0.5
ld:
  window: 100
  step: 20
  r2: 0.2
snmf:
  k_start: 2.0
  k_best: 5
  ploidy: 2
  repeats: 10
  k_end: 10.0
map:
  climate_extent: auto
  gap: 0.5
  resolution: 0.5
  zoom_extent: 'NULL'
climate:
  enabled: 'true'
  predictors: bio_1,bio_2,bio_3,bio_4,bio_8,bio_9,bio_10,bio_12,bio_14,bio_15
pop:
  calc_stats: 'false'
  window_size: 3000000
  custom_trait_file: 'NULL'
piemap:
  alpha: 0.6
  show_labels: 'false'
  label_size: 8
  pie_scale: 1.0
  use_points: 'false'
ld_decay:
  group_by: site
  min_samples: 10
  max_distance: 500
  scope: both
association:
  configs:
  - method: EMMAX
    adjust: bonf
    threshold: '0.05'
  - method: LFMM
    adjust: bonf
    threshold: '0.05'
  combine_method: Sum
  combine_gap: 100000
  sig_snp_distance: 100000
  region_distance: 2000000
  top_regions: 10
  promoter_length: 10000
  go_field: ontology
  scattermore_threshold: 30000
gff:
  feature: mRNA
  gene_name: description
  biotype: biotype
enrichment:
  top_terms: 20
  plot_width: 12
  plot_height: 10
  cnet_label: gene_id
  top_plot_regions: 5
regionplot:
  region: chr3H:108816722-117816722
  traits: GS_Mean_Mbp,Grain_weight
  method: EMMAX
  genes: all
future:
  ssp: '585'
  year: 2061-2080
  models: MPI-ESM1-2-HR,UKESM1-0-LL,IPSL-CM6A-LR
gradient_forest:
  ntree: '1000'
  cor_threshold: '0.5'
  spatial_correction: with
  run_label: EMMAX_bonf005
  random_model: 'true'
overlap:
  pairwise:
    window_size: 500000
    min_snps: 2
