input:
  dir: data/
  vcf: Arabidopsis_1001G_thin100mb.vcf
  metadata: Arabidopsis_1001G_metadata.tsv
  gff: Arabidopsis_1001G.gff3
project_name: Arabidopsis
cpu: 10
filter:
  maf: 0.05
  snp_miss: 0.1
  sample_miss: 0.5
ld:
  window: 100
  step: 20
  r2: 0.2
snmf:
  k_start: 2
  k_end: 10
  k_best: 5
  ploidy: 2
  repeats: 10
map:
  climate_extent: auto
  gap: 2.0
  resolution: 2.5
  zoom_extent: 'NULL'
climate:
  enabled: 'true'
  predictors: bio_1,bio_2,bio_3,bio_4,bio_8,bio_9,bio_10,bio_12,bio_14,bio_15
pop:
  calc_stats: 'true'
  window_size: 3000000
  custom_trait_file: 'NULL'
piemap:
  alpha: 0.6
  show_labels: F
  label_size: 3
  pie_scale: 0.8
  use_points: 'false'
ld_decay:
  group_by: site
  min_samples: 5
  max_distance: 500
  scope: both
association:
  configs:
  - method: EMMAX
    adjust: bonf
    threshold: '0.05'
  - method: LFMM
    adjust: bonf
    threshold: '0.05'
  - method: BLINK
    adjust: bonf
    threshold: '0.05'
  combine_method: Sum
  combine_gap: 100000
  sig_snp_distance: 100000
  region_distance: 500000
  top_regions: 10
  promoter_length: 2000
  go_field: 'NULL'
  scattermore_threshold: 15000
gff:
  feature: gene
  gene_name: description
  biotype: biotype
enrichment:
  top_terms: 20
  plot_width: 12
  plot_height: 10
  cnet_label: gene_id
  top_plot_regions: 0
regionplot:
  region: 'NULL'
  traits: 'NULL'
  method: 'NULL'
  genes: all
future:
  ssp: '585'
  year: 2061-2080
  models: MPI-ESM1-2-HR
gradient_forest:
  ntree: '500'
  cor_threshold: '0.5'
  spatial_correction: with
  run_label: Arabidopsis_1001G
  random_model: 'true'
phenotype_association:
  configs:
  - method: EMMAX
    adjust: bonf
    threshold: '0.05'
  - method: BLINK
    adjust: bonf
    threshold: '0.05'
  missing_strategy: MEAN
overlap:
  pairwise:
    window_size: 500000
    min_snps: 2
